# Generated by Django 5.2.16 on 2026-07-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecoutant',
            name='institution_partenaire',
            field=models.CharField(blank=True, help_text='Fac de psychologie ou ONG ayant prÃ©-validÃ© le volontaire.', max_length=150),
        ),
        migrations.AlterField(
            model_name='ecoutant',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'ValidÃ©'), ('refuse', 'RefusÃ©'), ('probatoire', 'PÃ©riode probatoire')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='superviseur',
            name='est_psychologue',
            field=models.BooleanField(default=False, help_text='Un superviseur peut aussi Ãªtre le psychologue rÃ©fÃ©rent.'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='securite_biometrique_active',
            field=models.BooleanField(default=False, help_text="Double sÃ©curitÃ© Face ID + mot de passe activÃ©e par l'ado."),
        ),
    ]
