# Generated by Django 5.2.16 on 2026-07-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_langue_preferee_ecoutant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoutant',
            name='langue_preferee',
            field=models.CharField(blank=True, choices=[('fr', 'Francais'), ('en', 'English')], default='fr', max_length=10),
        ),
    ]
