# Generated by Django 5.2.16 on 2026-09-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ecoutant_langue_preferee'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologuepartenaire',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
