# Generated by Django 5.2.16 on 2026-09-17 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_psychologuepartenaire_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoutant',
            name='date_entretien',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecoutant',
            name='email_invitation_envoyee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ecoutant',
            name='lieu_entretien',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ecoutant',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1),
        ),
        migrations.AddField(
            model_name='psychologuepartenaire',
            name='date_entretien',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psychologuepartenaire',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psychologuepartenaire',
            name='email_invitation_envoyee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='psychologuepartenaire',
            name='lieu_entretien',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='psychologuepartenaire',
            name='mot_de_passe_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='psychologuepartenaire',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1),
        ),
        migrations.AddField(
            model_name='psychologuepartenaire',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='ecoutant',
            name='institution_partenaire',
            field=models.CharField(blank=True, help_text='Fac de psychologie ou ONG ayant pré-validé le volontaire.', max_length=150),
        ),
        migrations.AlterField(
            model_name='ecoutant',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('probatoire', 'Période probatoire')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='psychologuepartenaire',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 17, 10, 58, 49, 913501, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='superviseur',
            name='est_psychologue',
            field=models.BooleanField(default=False, help_text='Un superviseur peut aussi être le psychologue référent.'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='securite_biometrique_active',
            field=models.BooleanField(default=False, help_text="Double sécurité Face ID + mot de passe activée par l'ado."),
        ),
    ]
