# Generated by Django 5.2.16 on 2026-07-18 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_creneau', models.CharField(choices=[('cercle', 'Cercle d’écoute'), ('seance_physique', 'Séance physique (psychologue certifié uniquement)')], max_length=20)),
                ('jour_semaine', models.PositiveSmallIntegerField(help_text='0 = lundi ... 6 = dimanche')),
                ('heure', models.TimeField()),
                ('lieu_institutionnel', models.CharField(blank=True, help_text='Obligatoire pour une séance physique — jamais un lieu privé.', max_length=150)),
                ('cercle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messagerie.cercleecoute')),
                ('ecoutant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='accounts.ecoutant')),
                ('psychologue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='accounts.psychologuepartenaire')),
            ],
        ),
    ]
