# Generated by Django 5.2.16 on 2026-07-18 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntreeJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humeur', models.CharField(choices=[('content', 'Content'), ('neutre', 'Neutre'), ('triste', 'Triste'), ('colere', 'En colère'), ('fatigue', 'Fatigué')], max_length=20)),
                ('texte', models.TextField(blank=True)),
                ('fichier_audio', models.FileField(blank=True, null=True, upload_to='journal/audio/%Y/%m/')),
                ('fichier_photo', models.ImageField(blank=True, null=True, upload_to='journal/photos/%Y/%m/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrees_journal', to='accounts.utilisateur')),
            ],
            options={
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', '-date_creation'], name='journal_ent_utilisa_b5925d_idx')],
            },
        ),
    ]
