# Generated by Django 5.2.16 on 2026-07-18 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CercleEcoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(help_text='Ex : "Pression scolaire", "Solitude", "Violences à la maison"', max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ecoutant_animateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cercles_animes', to='accounts.ecoutant')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', "En attente d'un écoutant"), ('en_cours', 'En cours'), ('cloturee', 'Clôturée')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_activite', models.DateTimeField(auto_now=True)),
                ('ecoutant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='accounts.ecoutant')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.utilisateur')),
            ],
            options={
                'ordering': ['-date_derniere_activite'],
            },
        ),
        migrations.CreateModel(
            name='MessageCercle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('cercle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messagerie.cercleecoute')),
                ('ecoutant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ecoutant')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.utilisateur')),
            ],
            options={
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='MembreCercle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adhesion', models.DateTimeField(auto_now_add=True)),
                ('cercle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='messagerie.cercleecoute')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.utilisateur')),
            ],
            options={
                'unique_together': {('cercle', 'utilisateur')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(choices=[('utilisateur', 'Ado'), ('ecoutant', 'Écoutant')], max_length=20)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('signale_par_module_ia', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messagerie.conversation')),
            ],
            options={
                'ordering': ['date_envoi'],
                'indexes': [models.Index(fields=['conversation', 'date_envoi'], name='messagerie__convers_7584d1_idx')],
            },
        ),
    ]
