# Generated by Django 6.0.7 on 2026-07-22 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ecoutant_langue_preferee'),
        ('messagerie', '0002_message_lu'),
    ]

    operations = [
        migrations.AddField(
            model_name='cercleecoute',
            name='restreint',
            field=models.BooleanField(default=False, help_text='Si vrai, seuls les écoutants peuvent parler'),
        ),
        migrations.CreateModel(
            name='ConversationAdoAdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_activite', models.DateTimeField(auto_now=True)),
                ('cercle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_ado', to='messagerie.cercleecoute')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_ado_recues', to='accounts.utilisateur')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_ado_envoyees', to='accounts.utilisateur')),
            ],
            options={
                'ordering': ['-date_derniere_activite'],
                'unique_together': {('expediteur', 'destinataire', 'cercle')},
            },
        ),
        migrations.CreateModel(
            name='MessageAdoAdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.utilisateur')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messagerie.conversationadoado')),
            ],
            options={
                'ordering': ['date_envoi'],
            },
        ),
    ]
