# Generated by Django 5.2.16 on 2026-09-17 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0003_cercleecoute_restreint_conversationadoado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(help_text='Note de 1 à 5')),
                ('commentaire', models.TextField(blank=True)),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='messagerie.conversation')),
            ],
        ),
    ]
