# Generated by Django 5.2.16 on 2026-07-18 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ecoutant', 'Signalée par un écoutant'), ('module_ia', 'Détectée par le module de supervision')], max_length=20)),
                ('gravite', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('urgent', 'Urgent')], max_length=20)),
                ('description', models.TextField(help_text="Ce qui inquiète l'écoutant, ou le motif détecté par le module IA.")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('cloturee', 'Clôturée')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('justification_traitement', models.TextField(blank=True, help_text='Traçabilité : pourquoi cette décision a été prise (exigence du cahier des charges).')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='messagerie.conversation')),
                ('superviseur_assigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_traitees', to='accounts.superviseur')),
            ],
            options={
                'ordering': ['-gravite', '-date_creation'],
                'indexes': [models.Index(fields=['statut', 'gravite'], name='alertes_ale_statut_970ad5_idx')],
            },
        ),
    ]
