# Generated by Django 5.2.16 on 2026-07-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('type_ressource', models.CharField(choices=[('psychologue', 'Psychologue'), ('ong', 'ONG'), ('centre', "Centre d'écoute")], max_length=20)),
                ('ville', models.CharField(max_length=80)),
                ('contact', models.CharField(blank=True, max_length=150)),
                ('partenaire_certifie', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ville', 'nom'],
            },
        ),
    ]
